/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mark_liblame_LameEncoder */

#ifndef _Included_com_mark_liblame_LameEncoder
#define _Included_com_mark_liblame_LameEncoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mark_liblame_LameEncoder
 * Method:    lameInit
 * Signature: (IIIII)I
 */
JNIEXPORT jint JNICALL Java_com_mark_liblame_LameEncoder_lameInit
  (JNIEnv *env, jobject obj, jint in_sample_rate, jint in_channel, jint in_bit_rate, jint mode, jint quality);

/*
 * Class:     com_mark_liblame_LameEncoder
 * Method:    lameEncode
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_mark_liblame_LameEncoder_lameEncode
  (JNIEnv *env, jobject obj, jstring src_file_path, jstring target_file_path);

/*
 * Class:     com_mark_liblame_LameEncoder
 * Method:    close
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_mark_liblame_LameEncoder_lameClose
  (JNIEnv *env, jobject obj);

#ifdef __cplusplus
}
#endif
#endif
